version: "3.9"

services:

  db:
    image: postgres:17
    container_name: store_way_db

    restart: unless-stopped

    environment:
      POSTGRES_DB: storeway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: store_way_backend

    restart: unless-stopped

    env_file:
      - ./backend/.env

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app
      - ./backend/app/static/uploads:/app/app/static/uploads

    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
