"""delete collection product table

Revision ID: 0870121fc7d5
Revises: d67efbc9ab04
Create Date: 2025-11-24 19:22:45.227065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0870121fc7d5'
down_revision: Union[str, Sequence[str], None] = 'd67efbc9ab04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_variants_collection_id'), table_name='product_variants')
    op.drop_constraint(op.f('product_variants_collection_id_fkey'), 'product_variants', type_='foreignkey')
    op.drop_column('product_variants', 'collection_id')
    op.add_column('products', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_collection_id'), 'products', ['collection_id'], unique=False)
    op.create_foreign_key(None, 'products', 'collection_categories', ['collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_collection_id'), table_name='products')
    op.drop_column('products', 'collection_id')
    op.add_column('product_variants', sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('product_variants_collection_id_fkey'), 'product_variants', 'collection_categories', ['collection_id'], ['id'])
    op.create_index(op.f('ix_product_variants_collection_id'), 'product_variants', ['collection_id'], unique=False)
    # ### end Alembic commands ###
