"""delete collection product table try 3..

Revision ID: 3674a2daccd1
Revises: 0870121fc7d5
Create Date: 2025-11-24 19:28:36.886658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3674a2daccd1'
down_revision: Union[str, Sequence[str], None] = '0870121fc7d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_collection_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'collections', ['collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_collection_id_fkey'), 'products', 'collection_categories', ['collection_id'], ['id'])
    # ### end Alembic commands ###
