"""collection relation category

Revision ID: 3bcf62a3f8fb
Revises: 3cf96862c03a
Create Date: 2025-11-23 22:14:30.163133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bcf62a3f8fb'
down_revision: Union[str, Sequence[str], None] = '3cf96862c03a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_relations_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_category_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_category_id'], ['collection_categories.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_relations_category_collection_category_id'), 'collection_relations_category', ['collection_category_id'], unique=False)
    op.create_index(op.f('ix_collection_relations_category_collection_id'), 'collection_relations_category', ['collection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_relations_category_collection_id'), table_name='collection_relations_category')
    op.drop_index(op.f('ix_collection_relations_category_collection_category_id'), table_name='collection_relations_category')
    op.drop_table('collection_relations_category')
    # ### end Alembic commands ###
