"""photos

Revision ID: 3cf96862c03a
Revises: 7c7f1ae61156
Create Date: 2025-11-23 22:08:42.019997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf96862c03a'
down_revision: Union[str, Sequence[str], None] = '7c7f1ae61156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('collections', sa.Column('collection_category_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_collections_collection_category_id'), 'collections', ['collection_category_id'], unique=False)
    op.create_foreign_key(None, 'collections', 'collection_categories', ['collection_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collections', type_='foreignkey')
    op.drop_index(op.f('ix_collections_collection_category_id'), table_name='collections')
    op.drop_column('collections', 'collection_category_id')
    op.drop_table('collection_categories')
    # ### end Alembic commands ###
