"""initial

Revision ID: 5f1906292d97
Revises: 6036bedd0891
Create Date: 2025-12-24 17:47:09.477169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f1906292d97'
down_revision: Union[str, Sequence[str], None] = '6036bedd0891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_categories', sa.Column('slug', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_categories', 'slug')
    # ### end Alembic commands ###
