"""photos

Revision ID: 600e23463979
Revises: b3fb6455229e
Create Date: 2025-11-23 18:26:40.371013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '600e23463979'
down_revision: Union[str, Sequence[str], None] = 'b3fb6455229e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_products', sa.Column('photo_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_collection_products_collection_id'), 'collection_products', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_products_photo_id'), 'collection_products', ['photo_id'], unique=False)
    op.create_index(op.f('ix_collection_products_product_id'), 'collection_products', ['product_id'], unique=False)
    op.create_foreign_key(None, 'collection_products', 'photos', ['photo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collection_products', type_='foreignkey')
    op.drop_index(op.f('ix_collection_products_product_id'), table_name='collection_products')
    op.drop_index(op.f('ix_collection_products_photo_id'), table_name='collection_products')
    op.drop_index(op.f('ix_collection_products_collection_id'), table_name='collection_products')
    op.drop_column('collection_products', 'photo_id')
    # ### end Alembic commands ###
