"""initial

Revision ID: 6036bedd0891
Revises: 830f11404454
Create Date: 2025-12-22 12:45:12.853549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6036bedd0891'
down_revision: Union[str, Sequence[str], None] = '830f11404454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_product_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('base_category_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['base_category_id'], ['base_categories.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_product_limits_base_category_id'), 'collection_product_limits', ['base_category_id'], unique=False)
    op.create_index(op.f('ix_collection_product_limits_collection_id'), 'collection_product_limits', ['collection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_product_limits_collection_id'), table_name='collection_product_limits')
    op.drop_index(op.f('ix_collection_product_limits_base_category_id'), table_name='collection_product_limits')
    op.drop_table('collection_product_limits')
    # ### end Alembic commands ###
