"""Название миграции

Revision ID: 6646b2e0ecc0
Revises: 
Create Date: 2026-06-19 20:17:24.499184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6646b2e0ecc0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('hex_code', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colors_title'), 'colors', ['title'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('collection_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_category_id'], ['collection_categories.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_collection_category_id'), 'collections', ['collection_category_id'], unique=False)
    op.create_index(op.f('ix_collections_photo_id'), 'collections', ['photo_id'], unique=False)
    op.create_table('sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('base_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['base_category_id'], ['base_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sizes_base_category_id'), 'sizes', ['base_category_id'], unique=False)
    op.create_index(op.f('ix_sizes_title'), 'sizes', ['title'], unique=False)
    op.create_table('sub_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['base_category_id'], ['base_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_categories_base_category_id'), 'sub_categories', ['base_category_id'], unique=False)
    op.create_table('collection_product_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('base_category_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['base_category_id'], ['base_categories.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'base_category_id')
    )
    op.create_index(op.f('ix_collection_product_limits_base_category_id'), 'collection_product_limits', ['base_category_id'], unique=False)
    op.create_index(op.f('ix_collection_product_limits_collection_id'), 'collection_product_limits', ['collection_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_category_id', sa.Integer(), nullable=True),
    sa.Column('sub_category_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('simple_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['base_category_id'], ['base_categories.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['sub_category_id'], ['sub_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_base_category_id'), 'products', ['base_category_id'], unique=False)
    op.create_index(op.f('ix_products_collection_id'), 'products', ['collection_id'], unique=False)
    op.create_index(op.f('ix_products_material_id'), 'products', ['material_id'], unique=False)
    op.create_index(op.f('ix_products_sub_category_id'), 'products', ['sub_category_id'], unique=False)
    op.create_table('product_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_photos_photo_id'), 'product_photos', ['photo_id'], unique=False)
    op.create_index(op.f('ix_product_photos_product_id'), 'product_photos', ['product_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('size_id', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('price_modifier', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'size_id', 'color_id')
    )
    op.create_index(op.f('ix_product_variants_color_id'), 'product_variants', ['color_id'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_size_id'), 'product_variants', ['size_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_variants_size_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_color_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_product_photos_product_id'), table_name='product_photos')
    op.drop_index(op.f('ix_product_photos_photo_id'), table_name='product_photos')
    op.drop_table('product_photos')
    op.drop_index(op.f('ix_products_sub_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_material_id'), table_name='products')
    op.drop_index(op.f('ix_products_collection_id'), table_name='products')
    op.drop_index(op.f('ix_products_base_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_collection_product_limits_collection_id'), table_name='collection_product_limits')
    op.drop_index(op.f('ix_collection_product_limits_base_category_id'), table_name='collection_product_limits')
    op.drop_table('collection_product_limits')
    op.drop_index(op.f('ix_sub_categories_base_category_id'), table_name='sub_categories')
    op.drop_table('sub_categories')
    op.drop_index(op.f('ix_sizes_title'), table_name='sizes')
    op.drop_index(op.f('ix_sizes_base_category_id'), table_name='sizes')
    op.drop_table('sizes')
    op.drop_index(op.f('ix_collections_photo_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_collection_category_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_table('users')
    op.drop_table('photos')
    op.drop_table('materials')
    op.drop_index(op.f('ix_colors_title'), table_name='colors')
    op.drop_table('colors')
    op.drop_table('collection_categories')
    op.drop_table('base_categories')
    # ### end Alembic commands ###
