"""photos

Revision ID: 7c7f1ae61156
Revises: 600e23463979
Create Date: 2025-11-23 18:41:05.122891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c7f1ae61156'
down_revision: Union[str, Sequence[str], None] = '600e23463979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_products_photo_id'), table_name='collection_products')
    op.drop_constraint(op.f('collection_products_photo_id_fkey'), 'collection_products', type_='foreignkey')
    op.drop_column('collection_products', 'photo_id')
    op.add_column('collections', sa.Column('photo_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_collections_photo_id'), 'collections', ['photo_id'], unique=False)
    op.create_foreign_key(None, 'collections', 'photos', ['photo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collections', type_='foreignkey')
    op.drop_index(op.f('ix_collections_photo_id'), table_name='collections')
    op.drop_column('collections', 'photo_id')
    op.add_column('collection_products', sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('collection_products_photo_id_fkey'), 'collection_products', 'photos', ['photo_id'], ['id'])
    op.create_index(op.f('ix_collection_products_photo_id'), 'collection_products', ['photo_id'], unique=False)
    # ### end Alembic commands ###
