"""photos

Revision ID: b3fb6455229e
Revises: 98411f5df6ac
Create Date: 2025-11-23 16:19:22.797872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3fb6455229e'
down_revision: Union[str, Sequence[str], None] = '98411f5df6ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.add_column('product_photos', sa.Column('photo_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('product_photos_file_path_key'), 'product_photos', type_='unique')
    op.create_index(op.f('ix_product_photos_photo_id'), 'product_photos', ['photo_id'], unique=False)
    op.create_foreign_key(None, 'product_photos', 'photos', ['photo_id'], ['id'])
    op.drop_column('product_photos', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_photos', sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_photos', type_='foreignkey')
    op.drop_index(op.f('ix_product_photos_photo_id'), table_name='product_photos')
    op.create_unique_constraint(op.f('product_photos_file_path_key'), 'product_photos', ['file_path'], postgresql_nulls_not_distinct=False)
    op.drop_column('product_photos', 'photo_id')
    op.drop_table('photos')
    # ### end Alembic commands ###
