"""delete relation table

Revision ID: bde5d5853fe7
Revises: 3bcf62a3f8fb
Create Date: 2025-11-23 22:31:44.646413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bde5d5853fe7'
down_revision: Union[str, Sequence[str], None] = '3bcf62a3f8fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_relations_category_collection_category_id'), table_name='collection_relations_category')
    op.drop_index(op.f('ix_collection_relations_category_collection_id'), table_name='collection_relations_category')
    op.drop_table('collection_relations_category')
    op.add_column('collection_categories', sa.Column('sort_order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_categories', 'sort_order')
    op.create_table('collection_relations_category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('collection_category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_category_id'], ['collection_categories.id'], name=op.f('collection_relations_category_collection_category_id_fkey')),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('collection_relations_category_collection_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('collection_relations_category_pkey'))
    )
    op.create_index(op.f('ix_collection_relations_category_collection_id'), 'collection_relations_category', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_relations_category_collection_category_id'), 'collection_relations_category', ['collection_category_id'], unique=False)
    # ### end Alembic commands ###
