"""delete collection product table

Revision ID: d67efbc9ab04
Revises: bde5d5853fe7
Create Date: 2025-11-24 19:16:00.963153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd67efbc9ab04'
down_revision: Union[str, Sequence[str], None] = 'bde5d5853fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_products_collection_id'), table_name='collection_products')
    op.drop_index(op.f('ix_collection_products_product_id'), table_name='collection_products')
    op.drop_table('collection_products')
    op.add_column('product_variants', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_product_variants_collection_id'), 'product_variants', ['collection_id'], unique=False)
    op.create_foreign_key(None, 'product_variants', 'collection_categories', ['collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_variants', type_='foreignkey')
    op.drop_index(op.f('ix_product_variants_collection_id'), table_name='product_variants')
    op.drop_column('product_variants', 'collection_id')
    op.create_table('collection_products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('collection_products_collection_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('collection_products_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('collection_products_pkey'))
    )
    op.create_index(op.f('ix_collection_products_product_id'), 'collection_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_collection_products_collection_id'), 'collection_products', ['collection_id'], unique=False)
    # ### end Alembic commands ###
