"""delete collection product table try 3..

Revision ID: eb5ff0a7d8f2
Revises: 0870121fc7d5
Create Date: 2025-11-24 19:27:20.489701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb5ff0a7d8f2'
down_revision: Union[str, Sequence[str], None] = '0870121fc7d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('collections_collection_category_id_fkey'), 'collections', type_='foreignkey')
    op.create_foreign_key(None, 'collections', 'collections', ['collection_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collections', type_='foreignkey')
    op.create_foreign_key(op.f('collections_collection_category_id_fkey'), 'collections', 'collection_categories', ['collection_category_id'], ['id'])
    # ### end Alembic commands ###
